Support for old Py3.6 + howto
- downgraded some requirements; numpy > 1.21 didn't exist back then
- f"" strings didn't exist in Py3.6; the current edit would also work on
  newer python3's but yeah

Even with those edits it wouldn't build out of the box.
Steps on Ubuntu that led to a working editable (local) install of the
ppgplot module:

    ## if necessary
    #$> apt-get install python3-venv

    $> python3.6 -m venv /path/to/venv3.6
    $> . /path/to/venv3.6/bin/activate

    # Upgrade to newer pip (mine went from 9.* to 21.* or so b/c of requirement in pyproject.toml)
    # "You are using pip version 9.0.3, however version 25.0.1 is available."
    # "You should consider upgrading via the 'pip install --upgrade pip' command."
    (venv3.6) $> pip3.6 install --upgrade pip
    Downloading ...
    You are using pip version 21.3.1, however version 25.0.1 is available.
    (venv3.6) $> pip3.6 install --upgrade pip
    Requirement already satisfied: pip in /path/to/venv3.6/lib/python3.6/site-packages (21.3.1)

    # IDK if it installs the dependencies out of the box (I upgraded pip after
    # installing those dependencies manually - pip9.* didn't do it, and pip21.* said
    #  'oh already installed, don't have to do anything')
    # Just in case it doesn't auto-install:
    #(venv3.6) $> pip3.6 install numpy
    #(venv3.6) $> pip3.6 install pkgconfig

    # Now can build+link against local compilation of the giza lib
    # On this old system giza is not an apt installable package (yet) afaik
    # PGPLOT_DIR points at where giza was installed
    (venv3.6) $> PGPLOT_DIR=/path/to/some/giza pip3.6 install -v -e .

    # Now the module compiles & links but still won't install
    # Previous command terminates with:
    gcc [options] -o build/lib.linux-x86_64-3.6/ppgplot/_ppgplot.cpython-36m-x86_64-linux-gnu.so [more options]
    copying build/lib.linux-x86_64-3.6/ppgplot/_ppgplot.cpython-36m-x86_64-linux-gnu.so -> ppgplot
    error: could not create 'ppgplot/_ppgplot.cpython-36m-x86_64-linux-gnu.so': No such file or directory

    # So:
    (venv3.6) $> mkdir ppgplot

    # Repeat build+link
    (venv3.6) $> PGPLOT_DIR=/path/to/some/giza pip3.6 install -v -e .

    # Now there is a ppgplot/_ppgplot.cpython-.....so
    # Need to create a module out of it, using a very simple __init__.py

    (venv3.6) $> cd ppgplot
    (venv3.6) $> ln -s _ppgplot.cpython...so _ppgplot.so
    (venv3.6) $> echo "from ._ppgplot import *" > __init__.py

    # Testing it
    (venv3.6) $> cd /tmp
    (venv3.6) $> python3
    Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
    [GCC 7.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import ppgplot
    >>> print(ppgplot)
    <module 'ppgplot' from '/path/to/src/ppgplot/ppgplot/__init__.py'>
    >>> ppgplot.pgopen('/xw')
    >>>