Fix cibuildwheel step
This took a lot of time to figure out; several issues had to be
overcome.

giza-dev dependency not found when trying to cibuildwheel
---------------------------------------------------------

Linux:
Installing the giza-dev dependency on the runner's host-O/S does not make it
visible in the builder; cibuildwheel runs its builds into
yet-other-containers (multiple) images; these days based on Alma Linux.
That distro does not have giza-dev or giza-devel pkgs.
Solution: add a manual build step for Linux to pull giza tarball release
and build *inside* the build container (sheesh).
Support using yum or apt-get to install system dependencies.
See CIBW_BEFORE_ALL_LINUX.

MacOS:
the MacOS image has homebrew so can install deps there easily, no need
to build giza ourselves; see CIBW_BEFORE_ALL_MACOS
Follow advice from cibuild:repairwheel step:

    packages/delocate/delocating.py", line 925, in _check_and_update_wheel_name
          raise DelocationError(
     << many output skipped >>
      /private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/tmp7vjagw4l/wheel/ppgplot/.dylibs/libXext.6.dylib has a minimum target of 14.0
      Set the environment variable 'MACOSX_DEPLOYMENT_TARGET=14.0' to update minimum supported macOS for this wheel.
See CIBW_ENVIRONMENT_MACOS.

Upload wheels step fails
------------------------
At the end of a macos-latest buid got this error in the "upload wheels"
step:

    Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

Need to get separate artifacts per OS without name conflicts.
Fixed by adding a build matrix variable to the artefact name:

          name: python-pgplot-wheels-${{ matrix.os }}

Hardened build, add smoke-test
------------------------------
- restricted to "native" builds on MacOS, iso "universal" (homebrew
  don't do universal)
- make PKG_CONFIG path persist so it will be retained in wheel
- add smoke-test (CIBW_TEST_COMMAND)